language: node_js
node_js:
- 10.9.0
brancher:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_70e5cdf8cfb1_key -iv $encrypted_70e5cdf8cfb1_iv
  -in .travis/id_rsa_git.enc -out ~/.ssh/id_rsa_git -d
- chmod 600 ~/.ssh/id_rsa_git
install:
- npm install
before_script: 
script:
- npm run build
addons:
  ssh_known_hosts:
  - 182.92.75.69
after_success:
- pwd
- scp -r dist/ root@182.92.75.69:/nodeweb/ciweb/reactdemo/
